version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: . #if your Dockerfile is not at the same level change the path here (./frontend)
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
